site_name: pyresparser
nav:
    - Home: index.md
    - CLI: cli.md
repo_url: https://github.com/electivetechnology/cv-parser-python
site_author: Chris Dixon
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"